@startuml
title CalculatorEndToEndTest - no intensity data exists for calculation
participant "User"
participant "App"
participant "Octopus"
participant "National Grid"
"User" -> "App": POST octopus/charge-time
activate "App"
"App" -> "Octopus": GET {productCode}/electricity-tariffs/{tariffCode}/standard-unit-rates
activate "Octopus"

"Octopus" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "Octopus"
"App" -> "National Grid": GET intensity/{time}/fw48h
activate "National Grid"

"National Grid" X-[#FireBrick]> "App": <color:FireBrick> 500 Internal Server Error
deactivate "National Grid"
"App" X-[#FireBrick]> "User": <color:FireBrick> 500 Internal Server Error
deactivate "App"
@enduml