@startuml
title CalculatorEndToEndTest - responds with lowest intensity charge time using price limit
participant "User"
participant "App"
participant "Octopus"
participant "National Grid"
participant "Limit Calculator"
"User" -> "App": POST octopus/charge-time
activate "App"
"App" -> "Octopus": GET {productCode}/electricity-tariffs/{tariffCode}/standard-unit-rates
activate "Octopus"

"Octopus" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "Octopus"
"App" -> "National Grid": GET intensity/{from}/{to}
activate "National Grid"

"National Grid" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "National Grid"
"App" -> "Limit Calculator": POST calculate/price/{limit}
activate "Limit Calculator"

"Limit Calculator" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "Limit Calculator"
"App" -[#DarkGreen]> "User": <color:DarkGreen> 200 OK
deactivate "App"
@enduml