@startuml
title CalculatorEndToEndTest - responds with best charge time according to weights
participant "User"
participant "App"
participant "Octopus"
participant "National Grid"
participant "Weights Calculator"
"User" -> "App": POST octopus/charge-time
activate "App"
"App" -> "Octopus": GET {productCode}/electricity-tariffs/{tariffCode}/standard-unit-rates
activate "Octopus"

"Octopus" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "Octopus"
"App" -> "National Grid": GET intensity/{time}/fw48h
activate "National Grid"

"National Grid" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "National Grid"
"App" -> "Weights Calculator": POST calculate
activate "Weights Calculator"

"Weights Calculator" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "Weights Calculator"
"App" -[#DarkGreen]> "User": <color:DarkGreen> 200 OK
deactivate "App"
@enduml