@startuml
title EndToEndTest - calls scheduler to train for duration when best charge time is not found with end time and duration
participant "User"
participant "App"
participant "Scheduler"
"User" -> "App": POST charge-time
activate "App"
"App" -> "Scheduler": GET charge-time
activate "Scheduler"

"Scheduler" X-[#DarkOrange]> "App": <color:DarkOrange> 404 Not Found
deactivate "Scheduler"
"App" -> "Scheduler": PATCH intensities/train
activate "Scheduler"

"Scheduler" -[#DarkGreen]> "App": <color:DarkGreen> 204 No Content
deactivate "Scheduler"
"App" -> "Scheduler": GET charge-time
activate "Scheduler"

"Scheduler" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "Scheduler"
"App" -[#DarkGreen]> "User": <color:DarkGreen> 200 OK
deactivate "App"
@enduml