@startuml
title IntensitiesEndToEndTest - handles error from national grid with the correct response
participant "User"
participant "App"
participant "National Grid"
"User" -> "App": POST intensities
activate "App"
"App" -> "National Grid": GET intensity/{time}/fw48h
activate "National Grid"

"National Grid" X-[#FireBrick]> "App": <color:FireBrick> 500 Internal Server Error
deactivate "National Grid"
"App" X-[#DarkOrange]> "User": <color:DarkOrange> 404 Not Found
deactivate "App"
@enduml