@startuml
title IntensitiesEndToEndTest - returns intensity data from the scheduler
participant "User"
participant "App"
participant "Scheduler"
"User" -> "App": POST intensities
activate "App"
"App" -> "Scheduler": GET intensities
activate "Scheduler"

"Scheduler" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "Scheduler"
"App" -[#DarkGreen]> "User": <color:DarkGreen> 200 OK
deactivate "App"
@enduml