@startuml
title IntensitiesEndToEndTest - calls national grid and updates scheduler if scheduler is out of date
participant "User"
participant "App"
participant "Scheduler"
participant "National Grid"
"User" -> "App": POST intensities
activate "App"
"App" -> "Scheduler": GET intensities
activate "Scheduler"

"Scheduler" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "Scheduler"
"App" -> "National Grid": GET intensity/{time}/fw48h
activate "National Grid"

"National Grid" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "National Grid"
"App" -> "Scheduler": POST intensities
activate "Scheduler"

"Scheduler" -[#DarkGreen]> "App": <color:DarkGreen> 204 No Content
deactivate "Scheduler"
"App" -[#DarkGreen]> "User": <color:DarkGreen> 200 OK
deactivate "App"
@enduml