@startuml
title IntensitiesEndToEndTest - handles error when scheduler fails to accept data
participant "User"
participant "App"
participant "Scheduler"
participant "National Grid"
"User" -> "App": POST intensities
activate "App"
"App" -> "Scheduler": GET intensities
activate "Scheduler"

"Scheduler" X-[#DarkOrange]> "App": <color:DarkOrange> 404 Not Found
deactivate "Scheduler"
"App" -> "National Grid": GET intensity/{time}/fw48h
activate "National Grid"

"National Grid" -[#DarkGreen]> "App": <color:DarkGreen> 200 OK
deactivate "National Grid"
"App" -> "Scheduler": POST intensities
activate "Scheduler"

"Scheduler" X-[#DarkOrange]> "App": <color:DarkOrange> 400 Bad Request
deactivate "Scheduler"
"App" X-[#FireBrick]> "User": <color:FireBrick> 500 Internal Server Error
deactivate "App"
@enduml