@startuml
title OctopusTariffsEndToEndTest - handles invalid timestamps for start and end times
participant "User"
participant "App"
"User" -> "App": GET tariffs/{productCode}/{tariffCode}
activate "App"

"App" X-[#DarkOrange]> "User": <color:DarkOrange> 400 Bad Request
deactivate "App"
"User" -> "App": GET tariffs/{productCode}/{tariffCode}
activate "App"

"App" X-[#DarkOrange]> "User": <color:DarkOrange> 400 Bad Request
deactivate "App"
@enduml