@startuml
title OctopusTariffsEndToEndTest - handles failure case when unable to retrieve products
participant "User"
participant "App"
participant "Octopus"
"User" -> "App": GET tariffs
activate "App"
"App" -> "Octopus": GET 
activate "Octopus"

"Octopus" X-[#FireBrick]> "App": <color:FireBrick> 500 Internal Server Error
deactivate "Octopus"
"App" X-[#FireBrick]> "User": <color:FireBrick> 500 Internal Server Error
deactivate "App"
@enduml