@startuml
title OctopusTariffsEndToEndTest - handles tariff not existing
participant "User"
participant "App"
participant "Octopus"
"User" -> "App": GET tariffs/{productCode}/{tariffCode}
activate "App"
"App" -> "Octopus": GET {productCode}/electricity-tariffs/{tariffCode}/standard-unit-rates
activate "Octopus"

"Octopus" X-[#DarkOrange]> "App": <color:DarkOrange> 404 Not Found
deactivate "Octopus"
"App" X-[#DarkOrange]> "User": <color:DarkOrange> 404 Not Found
deactivate "App"
@enduml