@startuml
title OctopusTariffsEndToEndTest - handles octopus not responding
participant "User"
participant "App"
participant "Octopus"
"User" -> "App": GET tariffs/{productCode}/{tariffCode}
activate "App"
"App" -> "Octopus": GET AGILE-24-10-01/electricity-tariffs/E-1R-AGILE-24-10-01-D/standard-unit-rates/
activate "Octopus"

"Octopus" X-[#FireBrick]> "App": <color:FireBrick> 500 Internal Server Error
deactivate "Octopus"
"App" X-[#FireBrick]> "User": <color:FireBrick> 500 Internal Server Error
deactivate "App"
@enduml